### ISSUE TITLE
What is the licence?

### ISSUE THREAD

**Issue by jeroenrnl** [nuflix/library#1]
Hi, I would like to use a part of your project in one of my own projects. What is the licence you are publishing this under? My project http://www.zoph.org is GPLv2 licensed.

**Comment by nuflix** [comment]
Thanks for asking, I will put the license right away. I will use GNU GPLv3. But you may use it any way you want, just don't republish and claim that it is yours. I'll be glad if my code can help you with your projects.

**Comment by jeroenrnl** [comment]
Hi @nuflix thanks for getting back to me so soon. I have added a text file giving you the credits. https://gitlab.com/jeroenrnl/zoph/-/tree/issue%2313/php/templates/default/images I've also added credits to the 'about' screen you can see in program.

BTW: the GPL _does_ allow people to republish files with your name removed. If you don't want that, you should probably use a Creative Commons Attribution Share Alike (CC-BY-SA) license or a BSD like license. Anyway, I'll be glad to credit you whether it's strictly necessary or not.

**Comment by nuflix** [comment]
Thanks for fair use and suggestions. I have learned some new things from you, so thank you very much.

**Comment by nuflix** [comment]
Now the license is there.
