### ISSUE TITLE
Step by .25 is sort of broken?

### ISSUE THREAD

**Issue by viraladmin** [nuflix/library#2]
So I have it set to do step by .25. 

At the whole and half numbers it works greats. (0, 0.5, 1, 1.5, etc).

At the point .25 level for some reason things start breaking down. I can't imagine a precision issue at this small of numbers... but what happens is: 

.25 is recorded as .23 and .75 is recorded as .73 (0, 0.23, .0.5, 0.73, 1, 1.23, 1.5 1.73, etc) 

As I intend to use this for gathering ratings, it means I have to intercept the .73 and .23, round them up, then pass them to the data-id and rating number manually to be correct. I can't figure out why .02 is being subtracted. Its clearly not a mathematical issue or it wouldn't be .02 being subtracted from both numbers. 

I have not modified the source in any way 

Suggestions?

**Comment by viraladmin** [comment]
So I have narrowed the problem down and it is in fact because a float is being lost, specifically it is parseInt(event.target.parentElement.style.width). 

The problem is that style.width will always return a rounded value not the actual value. This doesn't seem to be a problem with .5 because it will still always return a whole value unless ones width starts with a decimal. 

Still not sure how to get the actual value from style.width without it being rounded.

**Comment by viraladmin** [comment]
Ok so the problem is on line 146. You are using parseInt() which strips the px from the width but also strips decimals. 

So I replaced line 146 which was:

`event.target.parentElement.dataset.rating=(parseInt(event.target.parentElement.style.width)/parseInt(event.target.parentElement.style.backgroundSize)).toFixed(2);`

I replaced with:

```
var w = event.target.parentElement.style.width;
var x = w.substring(0, w.length - 2);
event.target.parentElement.dataset.rating=(x/parseInt(event.target.parentElement.style.backgroundSize)).toFixed(2);
```

This way we only strip the .px without removing the decimals and thus step .25 starts to return properly.

**Comment by nuflix** [comment]
Hello @viraladmin . Thank you for pointing out this problem. I had no idea it would behave like that for 0.25 and 0.75. I would like to modify code so that it works, but I'm relatively new on github and I don't know how exactly should I do that and be fair to you(the one who suggested it) ? Should I just mention you somewhere or there is some other way?

**Comment by viraladmin** [comment]
I am building this into a browser plugin that will be part of an upcoming cryptocurrency called TAC. The plugin will allow users to review and rate any website on the internet. Your star rating system is one of the methods that will be used in this process. I am not seeking any fame or glory, just wanted a proper working plugin. Just update your source, and close this comment. I need no credit, but maybe you will check out the project in a couple months :)

**Comment by nuflix** [comment]
I'm glad this project could be useful to somebody else :) I will probably update code in a few days. Also I would love to see your project when it is done !
